const nftData = [
    { 
        id: 1, 
        title: 'The Wonder', 
        price: '0.17 ETH', 
        imageUrl: 'https://nuron-nextjs.vercel.app/_next/image?url=%2Fimages%2Fportfolio%2Flg%2F1.jpg&w=640&q=75', 
        description: 'A rare 3D Ape with a unique hat and sunglasses.', 
        collection: '3D Apes Collection', 
        creator: 'Creator1', 
        owner: 'Owner1', 
        lastSoldPrice: '0.09 ETH', 
        totalSales: 5, 
        category: '3D Apes' 
    },
    { 
        id: 2, 
        title: 'The Eternal Pump', 
        price: '0.68 ETH', 
        imageUrl: 'https://react-bitakon.netlify.app/assets/img/bid/bid-img-15.jpg', 
        description: 'This 3D Ape sports a trendy jacket and gold chain.', 
        collection: '3D Apes Collection', 
        creator: 'Creator2', 
        owner: 'Owner2', 
        lastSoldPrice: '0.015 ETH', 
        totalSales: 3, 
        category: '3D Apes' 
    },
    { 
        id: 7963, 
        title: 'Preatent', 
        price: '0.31 ETH', 
        imageUrl: 'https://nuron-nextjs.vercel.app/_next/image?url=%2Fimages%2Fportfolio%2Flg%2Fportfolio-01.jpg&w=640&q=75', 
        description: 'An exclusive 3D Ape with a funky hairstyle.', 
        collection: '3D Apes Collection', 
        creator: 'Creator3', 
        owner: 'Owner3', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7964, 
        title: 'OrBid6', 
        price: '0.21 ETH', 
        imageUrl: 'https://nuron-nextjs.vercel.app/_next/image?url=%2Fimages%2Fportfolio%2Flg%2F2.jpg&w=640&q=75', 
        description: 'This 3D Ape is known for its stylish sneakers.', 
        collection: '3D Apes Collection', 
        creator: 'Creator4', 
        owner: 'Owner4', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7965, 
        title: 'Morgan11', 
        price: '0.15 ETH', 
        imageUrl: 'https://nuron-nextjs.vercel.app/_next/image?url=%2Fimages%2Fportfolio%2Flg%2F7.jpg&w=640&q=75', 
        description: 'A legendary 3D Ape with an iconic pose.', 
        collection: '3D Apes Collection', 
        creator: 'Creator5', 
        owner: 'Owner5', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7966, 
        title: 'Delta25', 
        price: '0.33 ETH', 
        imageUrl: 'https://nuron-nextjs.vercel.app/_next/image?url=%2Fimages%2Fportfolio%2Flg%2Fportfolio-02.jpg&w=640&q=75', 
        description: 'A cool 3D Ape with futuristic glasses.', 
        collection: '3D Apes Collection', 
        creator: 'Creator6', 
        owner: 'Owner6', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7967, 
        title: 'Preasent', 
        price: '0.41 ETH', 
        imageUrl: 'https://nuron-nextjs.vercel.app/_next/image?url=%2Fimages%2Fportfolio%2Flg%2F4.jpg&w=640&q=75', 
        description: 'This 3D Ape has a playful expression.', 
        collection: '3D Apes Collection', 
        creator: 'Creator7', 
        owner: 'Owner7', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7968, 
        title: 'Norgan12', 
        price: '0.52 ETH', 
        imageUrl: 'https://nuron-nextjs.vercel.app/_next/image?url=%2Fimages%2Fportfolio%2Flg%2F9.jpg&w=640&q=75', 
        description: 'A 3D Ape with a stunning tattoo on its arm.', 
        collection: '3D Apes Collection', 
        creator: 'Creator8', 
        owner: 'Owner8', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7969, 
        title: 'cAtal7', 
        price: '0.48 ETH', 
        imageUrl: 'https://nuron-nextjs.vercel.app/_next/image?url=%2Fimages%2Fportfolio%2Flg%2F5.jpg&w=640&q=75', 
        description: 'This 3D Ape is known for its charismatic smile.', 
        collection: '3D Apes Collection', 
        creator: 'Creator9', 
        owner: 'Owner9', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7961, 
        title: 'Pomeranian Doge', 
        price: '0.6 ETH', 
        imageUrl: 'https://enefti.modeltheme.com/wp-content/uploads/2022/08/2.jpg', 
        description: 'A 3D Ape that embodies street style.', 
        collection: '3D Apes Collection', 
        creator: 'Creator10', 
        owner: 'Owner10', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7930, 
        title: 'King Of Pirates', 
        price: '0.53 ETH', 
        imageUrl: 'https://enefti.modeltheme.com/wp-content/uploads/2022/08/10.jpg', 
        description: 'This 3D Ape has a distinctive look with a leather jacket.', 
        collection: '3D Apes Collection', 
        creator: 'Creator11', 
        owner: 'Owner11', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7940, 
        title: 'Super Saiyan Goku', 
        price: '0.32 ETH', 
        imageUrl: 'https://enefti.modeltheme.com/wp-content/uploads/2022/08/5.jpg', 
        description: 'A 3D Ape with an epic beard and glasses.', 
        collection: '3D Apes Collection', 
        creator: 'Creator12', 
        owner: 'Owner12', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7950, 
        title: 'Nintendo Switch', 
        price: '0.66 ETH', 
        imageUrl: 'https://enefti.modeltheme.com/wp-content/uploads/2022/08/3.jpg', 
        description: 'A 3D Ape with a vibrant color palette.', 
        collection: '3D Apes Collection', 
        creator: 'Creator13', 
        owner: 'Owner13', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7960, 
        title: 'Black Swordsman', 
        price: '0.2 ETH', 
        imageUrl: 'https://enefti.modeltheme.com/wp-content/uploads/2022/08/6.jpg', 
        description: 'This 3D Ape has a futuristic look with cybernetic enhancements.', 
        collection: '3D Apes Collection', 
        creator: 'Creator14', 
        owner: 'Owner14', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7970, 
        title: 'Aschfahler Ritter', 
        price: '0.44 ETH', 
        imageUrl: 'https://enefti.modeltheme.com/wp-content/uploads/2022/08/8.jpg', 
        description: 'A mysterious 3D Ape with a dark cloak.', 
        collection: '3D Apes Collection', 
        creator: 'Creator15', 
        owner: 'Owner15', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7980, 
        title: 'Pixel Art Addicted', 
        price: '0.71 ETH', 
        imageUrl: 'https://enefti.modeltheme.com/wp-content/uploads/2022/08/9.jpg', 
        description: 'This 3D Ape is always ready for action with its armor.', 
        collection: '3D Apes Collection', 
        creator: 'Creator16', 
        owner: 'Owner16', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7990, 
        title: 'The Strange Art', 
        price: '0.34 ETH', 
        imageUrl: 'https://enefti.modeltheme.com/wp-content/uploads/2022/08/4.jpg', 
        description: 'A cheerful 3D Ape with a big smile and headphones.', 
        collection: '3D Apes Collection', 
        creator: 'Creator17', 
        owner: 'Owner17', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7900, 
        title: 'SKISIRS Snake', 
        price: '0.59 ETH', 
        imageUrl: 'https://binaboxnextjs.vercel.app/assets/images/item-details.jpg', 
        description: 'This 3D Ape is always on the go with its skateboard.', 
        collection: '3D Apes Collection', 
        creator: 'Creator18', 
        owner: 'Owner18', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7910, 
        title: 'Nitro Grey', 
        price: '0.5 ETH', 
        imageUrl: 'https://binaboxnextjs.vercel.app/assets/images/product/product6.jpg', 
        description: 'A calm and composed 3D Ape with a zen attitude.', 
        collection: '3D Apes Collection', 
        creator: 'Creator19', 
        owner: 'Owner19', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7160, 
        title: 'Thunderbolt', 
        price: '0.79 ETH', 
        imageUrl: 'https://binaboxnextjs.vercel.app/assets/images/product/product7.jpg', 
        description: 'A stylish 3D Ape with a taste for luxury.', 
        collection: '3D Apes Collection', 
        creator: 'Creator20', 
        owner: 'Owner20', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7260, 
        title: 'Golden Shield', 
        price: '0.61 ETH', 
        imageUrl: 'https://binaboxnextjs.vercel.app/assets/images/product/product4.jpg', 
        description: 'A 3D Ape with an electrifying personality.', 
        collection: '3D Apes Collection', 
        creator: 'Creator21', 
        owner: 'Owner21', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7360, 
        title: 'Skullcrusher', 
        price: '0.42 ETH', 
        imageUrl: 'https://binaboxnextjs.vercel.app/assets/images/product/product3.jpg', 
        description: 'This 3D Ape is a true warrior with a battle-hardened look.', 
        collection: '3D Apes Collection', 
        creator: 'Creator22', 
        owner: 'Owner22', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7460, 
        title: 'Roboto', 
        price: '0.6 ETH', 
        imageUrl: 'https://binaboxnextjs.vercel.app/assets/images/product/product11.jpg', 
        description: 'A chill 3D Ape who loves music and relaxation.', 
        collection: '3D Apes Collection', 
        creator: 'Creator23', 
        owner: 'Owner23', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7560, 
        title: 'Killer quad', 
        price: '0.31 ETH', 
        imageUrl: 'https://binaboxnextjs.vercel.app/assets/images/product/product2.jpg', 
        description: 'A fun-loving 3D Ape who enjoys a good party.', 
        collection: '3D Apes Collection', 
        creator: 'Creator24', 
        owner: 'Owner24', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7560, 
        title: 'VZUS ambwe', 
        price: '0.37 ETH', 
        imageUrl: 'https://react-bitakon.netlify.app/assets/img/bid/bid-img-2.jpg', 
        description: 'A fun-loving 3D Ape who enjoys a good party.', 
        collection: '3D Apes Collection', 
        creator: 'Creator24', 
        owner: 'Owner24', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7560, 
        title: 'Meta Wolves Club', 
        price: '0.63 ETH', 
        imageUrl: 'https://react-bitakon.netlify.app/assets/img/bid/bid-img-1.jpg', 
        description: 'A fun-loving 3D Ape who enjoys a good party.', 
        collection: '3D Apes Collection', 
        creator: 'Creator24', 
        owner: 'Owner24', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7560, 
        title: 'Beach Moon Escape', 
        price: '0.56 ETH', 
        imageUrl: 'https://react-bitakon.netlify.app/assets/img/bid/bid-img-3.jpg', 
        description: 'A fun-loving 3D Ape who enjoys a good party.', 
        collection: '3D Apes Collection', 
        creator: 'Creator24', 
        owner: 'Owner24', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7560, 
        title: 'Aqua Watcher Genesis', 
        price: '0.58 ETH', 
        imageUrl: 'https://react-bitakon.netlify.app/assets/img/bid/bid-img-4.jpg', 
        description: 'A fun-loving 3D Ape who enjoys a good party.', 
        collection: '3D Apes Collection', 
        creator: 'Creator24', 
        owner: 'Owner24', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7560, 
        title: 'Chromie Squiggle', 
        price: '0.44 ETH', 
        imageUrl: 'https://react-bitakon.netlify.app/assets/img/bid/bid-img-13.jpg', 
        description: 'A fun-loving 3D Ape who enjoys a good party.', 
        collection: '3D Apes Collection', 
        creator: 'Creator24', 
        owner: 'Owner24', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
    { 
        id: 7560, 
        title: 'Project Crack', 
        price: '0.78 ETH', 
        imageUrl: 'https://react-bitakon.netlify.app/assets/img/bid/bid-img-12.jpg', 
        description: 'A fun-loving 3D Ape who enjoys a good party.', 
        collection: '3D Apes Collection', 
        creator: 'Creator24', 
        owner: 'Owner24', 
        lastSoldPrice: '0.00 ETH', 
        totalSales: 0, 
        category: '3D Apes' 
    },
];

export default nftData;